apiVersion: v1
kind: Service
metadata:
  name: order-web-service
  namespace: lnmp
spec:
  ports:
  - port: 8023
    name: order-web-service-8023
    protocol: TCP
    targetPort: 8023
    nodePort: 8023
  selector:
    app: order-web-pod
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-web-deployment
  namespace: lnmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-web-pod
  template:
    metadata:
      labels:
        app: order-web-pod
    spec:
      containers:
      - name: go-order-web
        image: images_order_web
        imagePullPolicy: Never
        ports:
        - containerPort: 8023